version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:8080'
      - '81:8181'
      - '443:6443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt